### ISSUE TITLE
Allow sports to be searchable 

### ISSUE THREAD

**Issue by alextoul** [Decathlon/sports-api-wrapper#2]
Decathlon::Sports.where(name: 'Snowboarding') 

Decathlon::Sports.find(71) isn't readable

**Comment by CaioBianchi** [comment]
This works with the `slug` property for now.
E.g.:

```ruby
Decathlon::Sports.find('snowboarding')
```

I'll improve it to be a bit smarter and query the elasticsearch index when a string is passed in.

**Comment by alextoul** [comment]
Cool! Not documented on developers.decathlon.com then ?

**Comment by CaioBianchi** [comment]
@alextoul The above PR adds a method that will search the index (via ElasticSearch) for the name of the sport via a `.search` method as such:

```ruby
Decathlon::Sports.search('snowboarding')
```
